workspace:
  base: /go
  path: src/github.com/kontena/kubelet-rubber-stamp

pipeline:
  test:
    image: golang:1.11
    commands:
      - mkdir -p /go/bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure -v -vendor-only
      - ./test.sh

  docker:
    group: image
    registry: quay.io
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/kubelet-rubber-stamp-amd64
    dockerfile: Dockerfile
    auto_tag: true

  docker-arm:
    group: image
    registry: quay.io
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/kubelet-rubber-stamp-arm64
    dockerfile: Dockerfile
    build_args:
      - ARCH=arm64
    auto_tag: true
